## PLACE FILE IN /etc/keyd/default.conf

[ids]
*
-dec0:5eba

[main]
leftmeta+leftalt = layer(lower_finnish)
leftmeta+leftshift = layer(upper_finnish)

[lower_finnish]
# G is the keyd symbol for AltGr
a = G-a
o = G-o

[upper_finnish]
a = G-S-a
o = G-S-o
